"""
PM25 Sensor Constants

This module contains all constants for the PM25 air quality sensor,
including register addresses and communication parameters.
Based on DFRobot AirQualitySensor implementation.
"""

# PM Concentration Type Registers
PARTICLE_PM1_0_STANDARD = 0x05
PARTICLE_PM2_5_STANDARD = 0x07
PARTICLE_PM10_STANDARD = 0x09
PARTICLE_PM1_0_ATMOSPHERE = 0x0B
PARTICLE_PM2_5_ATMOSPHERE = 0x0D
PARTICLE_PM10_ATMOSPHERE = 0x0F

# Particle Counting Registers
PARTICLENUM_0_3_UM_EVERY0_1L_AIR = 0x11
PARTICLENUM_0_5_UM_EVERY0_1L_AIR = 0x13
PARTICLENUM_1_0_UM_EVERY0_1L_AIR = 0x15
PARTICLENUM_2_5_UM_EVERY0_1L_AIR = 0x17
PARTICLENUM_5_0_UM_EVERY0_1L_AIR = 0x19
PARTICLENUM_10_UM_EVERY0_1L_AIR = 0x1B

# System Registers
PARTICLENUM_GAIN_VERSION = 0x1D

# Power Management Registers
POWER_MODE_REGISTER = 0x01
POWER_MODE_SLEEP = 0x01
POWER_MODE_WAKE = 0x02

# I2C Communication Constants
I2C_MODE = 1
DEFAULT_I2C_BUS = 1
DEFAULT_I2C_ADDRESS = 0x19

# Data Processing Constants
DATA_LENGTH_2_BYTES = 2
DATA_LENGTH_1_BYTE = 1
BYTE_SHIFT = 8

# Error Codes
ERROR_CODE = -1

# Sensor Specifications
MAX_PM_CONCENTRATION = 999  # μg/m³
MAX_PARTICLE_COUNT = 65535  # 16-bit max value
WARMUP_TIME_SECONDS = 5
MIN_READ_INTERVAL = 1  # seconds

# Particle Size Descriptions
PARTICLE_SIZES = {
    PARTICLENUM_0_3_UM_EVERY0_1L_AIR: "0.3μm",
    PARTICLENUM_0_5_UM_EVERY0_1L_AIR: "0.5μm", 
    PARTICLENUM_1_0_UM_EVERY0_1L_AIR: "1.0μm",
    PARTICLENUM_2_5_UM_EVERY0_1L_AIR: "2.5μm",
    PARTICLENUM_5_0_UM_EVERY0_1L_AIR: "5.0μm",
    PARTICLENUM_10_UM_EVERY0_1L_AIR: "10μm"
}

# PM Type Descriptions
PM_TYPES = {
    PARTICLE_PM1_0_STANDARD: "PM1.0 Standard",
    PARTICLE_PM2_5_STANDARD: "PM2.5 Standard",
    PARTICLE_PM10_STANDARD: "PM10 Standard",
    PARTICLE_PM1_0_ATMOSPHERE: "PM1.0 Atmospheric",
    PARTICLE_PM2_5_ATMOSPHERE: "PM2.5 Atmospheric",
    PARTICLE_PM10_ATMOSPHERE: "PM10 Atmospheric"
}

# Valid register addresses for validation
VALID_REGISTERS = [
    PARTICLE_PM1_0_STANDARD,
    PARTICLE_PM2_5_STANDARD,
    PARTICLE_PM10_STANDARD,
    PARTICLE_PM1_0_ATMOSPHERE,
    PARTICLE_PM2_5_ATMOSPHERE,
    PARTICLE_PM10_ATMOSPHERE,
    PARTICLENUM_0_3_UM_EVERY0_1L_AIR,
    PARTICLENUM_0_5_UM_EVERY0_1L_AIR,
    PARTICLENUM_1_0_UM_EVERY0_1L_AIR,
    PARTICLENUM_2_5_UM_EVERY0_1L_AIR,
    PARTICLENUM_5_0_UM_EVERY0_1L_AIR,
    PARTICLENUM_10_UM_EVERY0_1L_AIR,
    PARTICLENUM_GAIN_VERSION,
    POWER_MODE_REGISTER
]
